### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by edvwib** [edvwib/cyberlink#1]
# Assignment
You're going to create a Reddit clone. Prepare a short presentation of your project which you're going to present for the entire class on January 17, 2018. We'll collect the repository links on this day as well. Send the public GitHub repository link to Vincent Klaiber on Slack.
Make sure your project includes all the default features and any optional extra features. Please also make sure the all requirements are fulfilled before sending us your project.
**Note: Bonus points for consistent syntax including correct indentation, readable and well documented code!**

## Features
_Below you'll find a list of user stories. This is the behavior on how the user interact with the Cyberlink application. We'll test all these behaviors before giving grades._
- [x] As a user I should be able to create an account.
- [x] As a user I should be able to login.
- [x] As a user I should be able to logout.
- [x] As a user I should be able to edit my account email, password and biography.
- [x] As a user I should be able to upload a profile avatar image.
- [x] As a user I should be able to create new links with a title and description.
- [x] As a user I should be able to edit my links.
- [x] As a user I should be able to delete my links.
- [x] As a user I should be able to up and down vote links.

## Extra
_Below you'll find a list of extra features to add to your project. As long as you've added the features above, you can start adding extra features. You're free to come up with your own extra features._
- [x] As a user I should be able to comment on a link.
- [x] As a user I'm able to edit my comments.
- [x] As a user I'm able to delete my comments.
- [x] As a user I'm able to reply to comments.
- [x] As a user I'm able to resetting my password with email.
- [x] As a user I'm able to delete my account along with all links and comments.

## Requirements
_Below you'll find a list of requirements which need to be fulfilled in order to complete the project. If you have any questions, please contact Vincent Klaiber on Slack._

- [x] The project should implement nice looking graphical user interface.
**Note: You may use Bootstrap if you want too (without any custom jQuery code).**
- [x] The application should be written in HTML, CSS, JavaScript and PHP.
- [x] The application should not be built using jQuery.
- [x] The application should be built using a SQLite database with at least three different tables.
- [x] The application should be pushed to a public repository on GitHub.
- [x] The application should be responsive and work on mobile devices.
- [x] The application should be implement secure hashed passwords when signing up.
- [x] The project's PHP files should declare strict types.
- [x] The project can't contain any PHP errors, warning or notices.
_Tip: If you haven't already, update your php.ini configuration to display errors._
- [x] The project must be tested on at least two of your classmates computers.
**Note: Add the testers name to the README.md file.**
- [x] The repository should have at least 30 commits and not just one big commit.
- [x] The repository should contain the database file.
- [x] The repository must contain a README.md file with installation instructions and documentation.
_Tip: Visit awesome-readme to see a list of well written README.md files._
- [x] The repository must contain a LICENSE file.
**Note: This is important when working with open-source software.**
- [x] The repository must contain a .editorconfig file with your preferred settings.
_Tip: Don't forget to install the EditorConfig package for Atom or your editor of choice._
  
  
  ## Other
- [x] Give bio a limit on length.
- [x] Display errors when creating an account.
- [ ] Only display deleted posts on users page who has commented on it or who created it.
- [x] Find a way to validate links consistently.
